### ISSUE TITLE
Key Auth Headers not applied when using Azure Function plugin on route

### ISSUE THREAD

**Issue by Tim-Hodge** [Kong/kong-plugin-azure-functions#15]
Hi
I am using the azure-functions plugin along side 'key-auth' and 'acl' to protect some Azure Function HTTP endpoints.

Running Kong 2.1 on Kubernetes.
Azure Function v3 C#

**Expected**
key-auth headers to be available through HttpRequestMessage.Headers
Headers defined here: https://docs.konghq.com/hub/kong-inc/key-auth/#upstream-headers
```
x-consumer-id=<guid>  
x-consumer-username=my-consumer-username
```

**Actual**
No custom headers are available within AzF runtime on HttpRequestMessage.Headers

**Reproduce**
Calls to /echo have the expected headers.
Calls to /test execute the function, but the expected headers are not available in HttpRequest.Headers
Auth works as expected - fails if the api-key is not provided or consumer is not in the correct ACL.
```yaml
# host and fn name removed
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: http-auth
config:
  key_names:
  - api-key
plugin: key-auth

---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: test-acl
config: 
  allow:
  - my-consumer-group
  hide_groups_header: true
plugin: acl

---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: test-fn
config:
  functionname: <fn-name>
  appname: <my-function-app>
  apikey: <...>
plugin: azure-functions

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sandbox-route
  annotations:
    konghq.com/plugins: "test-fn, http-auth, test-acl"
    konghq.com/strip-path: "true"
spec:
  rules:
  - host: <test-host>
    http:
      paths:
      - path: /test
        backend:
          serviceName: httpbin
          servicePort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-echo
  annotations:
    konghq.com/plugins: "http-auth, sandbox-acl"
    konghq.com/strip-path: "true"
spec:
  rules:
  - host: <test-host>
    http:
      paths:
      - path: /echo
        backend:
          serviceName: echo
          servicePort: 80
```

I'm currently unable to tell if these headers are stripped/not included by the azure functions plugin, or if the azure functions runtime itself is stripping when proxied. Sending requests with custom headers directly to the fn (not via Kong) works as expected.
